name: Deploy Bot

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push docker image
        run: |
          # Build the Docker image
          docker build --no-cache -t ${{ secrets.DOCKER_USERNAME }}/elongpt:db-version .
          docker push ${{ secrets.DOCKER_USERNAME }}/elongpt:db-version

      - name: Deploy to remote server
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Pull and deploy the image with the manually created tag
            docker pull ${{ secrets.DOCKER_USERNAME }}/elongpt:db-version
            docker rm -f elongpt-bot || true
            docker run -d -t \
            -e OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} \
            -e DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }} \
            -e CMC_PRO_API_KEY=${{ secrets.CMC_PRO_API_KEY }} \
            -e VISION_BRAIN_API_URL=${{ secrets.VISION_BRAIN_API_URL }} \
            -e VISION_BRAIN_API_KEY=${{ secrets.VISION_BRAIN_API_KEY }} \
            -e BACKEND_API_URL=${{ secrets.BACKEND_API_URL }} \
            -e BACKEND_API_KEY=${{ secrets.BACKEND_API_KEY }} \
            --restart always \
            --name elongpt-bot \
            ${{ secrets.DOCKER_USERNAME }}/elongpt:db-version
