name: Deploy Bot

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Read Python version
        id: python_version
        run: |
          echo "PYTHON_VERSION=$(cat .python-version)" >> $GITHUB_ENV

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "${{ env.PYTHON_VERSION }}"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir -r requirements.txt

      - name: Format check
        run: |
          black --check .

      - name: Import order check
        run: |
          isort --check-only .

      - name: Linting check
        run: |
          flake8 .

  deploy:
    runs-on: ubuntu-latest
    environment: production
    needs: checks

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push docker image
        run: |
          # Build the Docker image
          docker build --no-cache -t ${{ secrets.DOCKER_USERNAME }}/elongpt:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/elongpt:latest

      - name: Deploy to remote server
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Pull and deploy the image with the manually created tag
            docker pull ${{ secrets.DOCKER_USERNAME }}/elongpt:latest
            docker rm -f elongpt-bot || true
            docker run -d -t \
            -e OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} \
            -e DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }} \
            -e CMC_PRO_API_KEY=${{ secrets.CMC_PRO_API_KEY }} \
            -e VISION_BRAIN_API_URL=${{ secrets.VISION_BRAIN_API_URL }} \
            -e VISION_BRAIN_API_KEY=${{ secrets.VISION_BRAIN_API_KEY }} \
            -e BACKEND_API_URL=${{ secrets.BACKEND_API_URL }} \
            -e BACKEND_API_KEY=${{ secrets.BACKEND_API_KEY }} \
            -e OLLAMA_SERVER=${{ secrets.OLLAMA_SERVER }} \
            -e OLLAMA_MODEL=${{ secrets.OLLAMA_MODEL }} \
            --restart always \
            --name elongpt-bot \
            ${{ secrets.DOCKER_USERNAME }}/elongpt:latest
